### PR TITLE
cocoa: remove dependency on nibs

### PR DESCRIPTION
**Pull request by sqweek**
This is a preliminary patch for issue #48 aimed at getting rid of the [NSNib initWithData] call which was only introduced in osx 10.8.

The approach I'm trying is to axe the nibs entirely; I seem to have the basics working, but some things have been lost (eg. the top-of-screen menu and the standard close/minimise/maximise buttons in the window title bar).

### CODE REVIEW

**Comment by tcolar** [comment]
So I tried this on Lion and it works great.

To be fair Lion is pretty old, it's just that the only mac I own currently can't run anything newer, so that's what I can test my stuff on, short of borrowing someone's newer mac.

So in any case if the NIB stuff is useful and needed, I would be OK with just a branch (or even fork) for this, whatever works best for you.

Thanks.

**Comment by sqweek** [comment]
Glad to hear it! Personally I've no qualms about axing the NIBs - I think it's a net simplification. Plus, creating menus/windows programatically opens up the option of providing an API for the application to customise things (although at this stage I can't see how to present such an API as useful in the wider cross-platform context).

Btw, you might be interested to know about [exp/shiny](http://github.com/golang/exp/tree/master/shiny), which is an up and coming package for dealing with screens and events. I've not got around to checking it out (I want to finish my current project using go.wde before going down that rabbit hole), but if I'm being honest it probably has a brighter future than go.wde thanks to its semi-official status and support for mobile targets.

**Comment by tcolar** [comment]
Yeah agree on first item. "Bare metal" minimalistic approach is what I like about go.wde.

I m aware of shiny but at this time it's a bit to experimental and not very go gettable. In my case I need little more than a window and events so go.wde might be alright for now.

**Comment by sqweek** [comment]
I've update the branch - title bar buttons are back and mouse enter/exit tracking is fixed (which was also causing SetCursor to behave oddly).

Also purged the remaining nib references from the codebase. Let me know if you notice anything acting funny, otherwise this is probably ready to go to master (although I should probably spend the time to add a few comments first ;) ).

**Comment by skelterjohn** [comment]
Yessss get rid of the nibs! They are a terrible dependency!

I once went over to #macdev and tried to get some help on this (like 5
years ago), but they absolutely refused. They said I should just write it
(as in, the whole program) in objc instead.

**Comment by tcolar** [comment]
@sqweek I'll try to test it some more later today.

@skelterjohn LOL, I'm sure nowadays they would still refuse and have you rewrite it in swift ;)

**Comment by sqweek** [comment]
Squashed onto master, I'll leave the individual commits here. Credit to:

http://www.cocoawithlove.com/2010/09/minimalist-cocoa-programming.html
https://github.com/golang/exp/blob/master/shiny/driver/gldriver/cocoa.m
https://github.com/9fans/plan9port/blob/master/src/cmd/devdraw/cocoa-screen.m

**Comment by tcolar** [comment]
Thanks, will test it tomorrow.

**Pull request closed without merging**
